# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(640, 459)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(208, 200, 215, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_name.setObjectName("line_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_name)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_pwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_pwd.setObjectName("line_pwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_pwd)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 110, 221, 71))
        self.label.setText("")

        self.label.setScaledContents(True)
        self.label.setPixmap(QtGui.QPixmap("/Users/zhb/Desktop/python-sdk-0.9.0/gui/fisco-bcos.png"))
        self.label.setObjectName("label")
        self.btn_login = QtWidgets.QToolButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(282, 279, 69, 32))
        self.btn_login.setObjectName("btn_login")
        self.btn_signup = QtWidgets.QToolButton(self.centralwidget)
        self.btn_signup.setGeometry(QtCore.QRect(195, 279, 69, 32))
        self.btn_signup.setObjectName("btn_signup")
        self.btn_quit = QtWidgets.QToolButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(370, 279, 69, 32))
        self.btn_quit.setObjectName("btn_quit")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_2.setText(_translate("Login", "用户名"))
        self.label_3.setText(_translate("Login", "密码"))
        self.btn_login.setText(_translate("Login", "登录"))
        self.btn_signup.setText(_translate("Login", "注册"))
        self.btn_quit.setText(_translate("Login", "退出"))
